### ISSUE TITLE
Multi Monitor Setup

### ISSUE THREAD

**Issue by Tom-Finke** [linux-surface/iptsd#155]
When connecting an external monitor, the stylus behaves as though both screens were one. Meaning when putting the stylus on the top right corner of the surface built in monitor the mouse moves to the top right of my external monitor. When moving the stylus to the bottom left of the built in monitor the mouse also moves to the bottom left of the built in monitor. Touch behaves the same way.
When stopping IPTSD, touch behaves corretly, meaning touch top right moves mouse to top right of built in monitor instead of external monitor

How can I configure IPTSD to only use the built in monitor for poisitioning the mouse? 
### Environment

- Hardware model: Surface Pro 8
- Kernel version: 6.4.12-surface
- Distribution: Ubuntu

**Comment by StollD** [comment]
I can't reproduce this on KDE Plasma Wayland.

Are you using Wayland or Xorg? Mapping inputs to the correct screen isn't the responsibility of the driver (iptsd in this case), but the desktop environment. I know that Xorg internally represents multiple monitors as one big one, so it would line up with what you are describing.

Have you checked if there is an option in the settings menu that allows you to map the touchscreen to a specific display? Do you have libwacom-surface installed, so the desktop can detect your touchscreen? (I didn't need libwacom-surface for KDE to recognize it, but idk about GNOME)

**Comment by Tom-Finke** [comment]
I'm on Xorg with Plasma DE.
I have libwacom installed, `libwacom-list-local-devices` gives me
```
/dev/input/event7 is a tablet but not supported by libwacom
devices:
- name: 'Microsoft Surface Pro 8'
  bus: 'unknown'
  vid: '0x045e'
  pid: '0x0c37'
  nodes:
  - /dev/input/event12: 'IPTS Stylus'
```

By the settings menu, do you mean plasmas systemsettings > Hardware > Input Devices >  Graphic Tablet? If so, no, the touchscreen is not listed there.
